### ISSUE TITLE
I am getting this errors when I run shinyloadtest_report(df, "report.html") 

### ISSUE THREAD

**Issue by omtarful** [rstudio/shinyloadtest#165] opened 2024-06-14 13:13 UTC
shinyloadtest_report(df, "report.html") 
report - Concurrency Legend [=====================================================================>---] 77/80 eta: 0sError in `gtable_trim()`:
! `x` must be a gtable object, not a <zeroGrob/grob/gDesc> object.
Run `rlang::last_trace()` to see where the error occurred.

**Comment by jzadra** [comment] 2024-06-20 23:57
I'm also having this issue.

R 4.3.0
shinyloadtest: 1.1.0
MacOS: 14.5 (23F79)

**Comment by kmcd39** [comment] 2024-06-21 15:44
Also having this issue. Nearly opened a separate issue about it.

My full error (a warning was also returned):

```
> test.report <- shinyloadtest::load_runs("run1")
> shinyloadtest::shinyloadtest_report(test.report, "run1.html")                                       
run1 - Concurrency Legend [=======================================================>] 413/416 eta: 1sError in `gtable_trim()`:
! `x` must be a gtable object, not a <zeroGrob/grob/gDesc> object.
Run `rlang::last_trace()` to see where the error occurred.
Warning message:
Returning more (or less) than 1 row per `summarise()` group was deprecated in dplyr 1.1.0.
ℹ Please use `reframe()` instead.
ℹ When switching from `summarise()` to `reframe()`, remember that `reframe()` always returns an
  ungrouped data frame and adjust accordingly.
ℹ The deprecated feature was likely used in the shinyloadtest package.
  Please report the issue at <https://github.com/rstudio/shinyloadtest/issues>.
```

**Comment by jcheng5** [comment] 2024-07-03 16:15
Sorry, I cannot reproduce this. Can someone email me at joe at posit dot co with a zipped up run directory?

**Comment by udurraniAtPresage** [comment] 2024-07-04 19:10
> Sorry, I cannot reproduce this. Can someone email me at joe at posit dot co with a zipped up run directory?

I sent you a zipped up run directory. Thanks for looking into this.

By the way, issue #163 is the same.

**Comment by jcheng5** [comment] 2024-07-05 20:27
Nice, I was able to reproduce it with that data once I updated ggplot2 and gtable. For reference, these versions worked fine:

```
 ggplot2         3.4.4      2023-10-12 [1] CRAN (R 4.3.1)
 gtable          0.3.4      2023-08-21 [1] CRAN (R 4.3.0)
```

**Comment by udurraniAtPresage** [comment] 2024-07-05 20:35
> Nice, I was able to reproduce it with that data once I updated ggplot2 and gtable. For reference, these versions worked fine:
> 
> ```
>  ggplot2         3.4.4      2023-10-12 [1] CRAN (R 4.3.1)
>  gtable          0.3.4      2023-08-21 [1] CRAN (R 4.3.0)
> ```

I have the same version of `gtable`, but my `ggplot2` version is 3.5.1. Hopefully, the fix will be quick. Thanks.

**Comment by jcheng5** [comment] 2024-07-08 17:47
Sorry about this, everyone--should be fixed now if you install from GitHub. You can also downgrade to ggplot2 3.4.x if that's an easier workaround.

**Closed by jcheng5** 2024-07-08 17:47 UTC
